version: '2.1'

services:
  flask_app:
    restart: always
    build: .
    ports:
      - 8000:5000
    volumes:
      - ./config.local.yml:/glider-dac-status/config.local.yml
      - ./glider-dac-status/web/static/json/status.json:/glider-dac-status/web/static/json/status.json
    depends_on:
      - redis
    command: gunicorn -w 4 -b "0.0.0.0:5000" app:app

  redis:
    restart: always
    image: redis
    volumes:
      - ./redis_data:/data:cached

  celery_worker:
    restart: always
    build: .
    volumes:
      - ./config.local.yml:/glider-dac-status/config.local.yml
      - ./glider-dac-status/web/static/json/status.json:/glider-dac-status/web/static/json/status.json
      - /tmp/web/static/profiles/:/glider-dac-status/web/static/profiles/
    depends_on:
      - redis
    command: celery worker -A app.celery --loglevel=info

  celery_beat:
    build: .
    volumes:
      - ./config.local.yml:/glider-dac-status/config.local.yml
    command: celery beat -A app.celery --loglevel=info

volumes:
  redis_data:
    external:
      name: redis_data